version: "3.8"
services:
  mysql8:
    image: mysql:8.0
    restart: always #mysql挂掉后自动重启
    command: --default-authentication-plugin=mysql_native_password #登录校验
    environment:
      MYSQL_ROOT_PASSWORD: "root" # 配置root用户密码
    volumes:
      - ./script/mysql:/docker-entrypoint-initdb.d/  #初始化脚本
    ports:
      - "3306:3306"
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=YES
    ports:
      - '6379:6379'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
      - "ES_JAVA-OPTS=-Xms84m Xmx512m"
    ports:
      - "9201:9200"
  etcd:
    image: "bitnami/etcd:latest"
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "2379:2379"

  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      #      - 三个分区
      - KAFKA_CREATE_TOPICS=webook_binlog:3:1
      #      - 允许自动创建 topic，线上不要开启
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
